### ISSUE TITLE
"To run this app, you must install .NET Core"

### ISSUE THREAD

**Issue by Deadfalt999** [libertyernie/goombasav#12]
While trying to open the app I keep having this message open, I have tried to install the latest version of said dependency but it doesn't seem to work. Perhaps you can provide some help ?

**Comment by shiftypickle88** [comment]
hey did you ever get a solution to your issue with ibrahim's better homebrew browser for vita?? i am having the exact same issue with the Vita-DB server instead of the CBPS-DB server that you seemed to be having an issue with, i opened as issue on ibrahim's project page but i a m yet to receive a reply
